//
// Created by LZR on 2021/3/10.
//

#ifndef CUDARAYTRACER_MACROS_H
#define CUDARAYTRACER_MACROS_H

// #define TEST
// #define TESTWORLDONLY
#define TRIANGLEWORLD
#define TESTMODEL
#define MORTON64

#endif //CUDARAYTRACER_MACROS_H
